version: '2.1'
services:

  history:
    image: <private-docker-registry>dojotraining/history:training-122018
    restart: always
    depends_on:
      - mongodb
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_SERVICE_MANAGEMENT: 'internal'
    logging:
      driver: json-file
      options:
        max-size: 100m

  persister:
    image: <private-docker-registry>dojotraining/persister:training-122018
    restart: always
    depends_on:
      - mongodb
      - auth
      - kafka
      - data-broker
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_SERVICE_MANAGEMENT: 'internal'
    logging:
      driver: json-file
      options:
        max-size: 100m

  mongodb:
    image: "<private-docker-registry>dojotraining/mongo:training-122018"
    restart: always
    user: "mongodb"
    logging:
      driver: json-file
      options:
        max-size: 100m

  gui:
    image: <private-docker-registry>dojotraining/gui:training-122018
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  data-broker:
    image: <private-docker-registry>dojotraining/data-broker:training-122018
    restart: always
    depends_on:
      - kafka
      - data-broker-redis
    logging:
      driver: json-file
      options:
        max-size: 100m

  data-broker-redis:
    image: <private-docker-registry>dojotraining/redis:training-122018
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  device-manager-redis:
    image: <private-docker-registry>dojotraining/redis:training-122018
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  device-manager:
    image: <private-docker-registry>dojotraining/device-manager:training-122018
    restart: always
    environment:
      # TODO: Fill these env variables with suitable values
      - DEV_MNGR_CRYPTO_PASS="kamehameHA"
      - DEV_MNGR_CRYPTO_IV=1234567890123456
      - DEV_MNGR_CRYPTO_SALT="shuriken"
    depends_on:
      - postgres
      - kafka
      - data-broker
      - device-manager-redis
    logging:
      driver: json-file
      options:
        max-size: 100m

  auth-redis:
    image: <private-docker-registry>dojotraining/redis:training-122018
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  auth:
    image: <private-docker-registry>dojotraining/auth:training-122018
    restart: always
    depends_on:
      - apigw
      - postgres
      - auth-redis
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AUTH_DB_HOST: "postgres"
      AUTH_DB_USER: "kong"
      AUTH_KONG_URL: "http://apigw:8001"
      AUTH_CACHE_HOST: "auth-redis"
      # This is used to select the type of cache to be used. Allowed values are "redis" or "nocache"
      AUTH_CACHE_NAME: "redis"
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres:
    image: "<private-docker-registry>dojotraining/postgres:training-122018"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres-users:
    image: "<private-docker-registry>dojotraining/postgres:training-122018"
    restart: on-failure
    command: >
      bash -c "createuser kong -d -h postgres -U postgres && createdb kong -U kong -h postgres"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-migration:
    image: <private-docker-registry>dojotraining/kong:training-122018
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
    command: kong migrations up
    restart: on-failure

  apigw:
    image: <private-docker-registry>dojotraining/kong:training-122018
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "postgres"
    volumes:
      - ./apigw/plugins/pep-kong:/plugins/pep-kong:Z
      - ./apigw/plugins/mutualauthentication:/plugins/mutualauthentication:Z
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-config:
    image: <private-docker-registry>dojotraining/curl:training-122018
    entrypoint: /opt/kong.config.sh
    restart: on-failure
    depends_on:
      - apigw
    volumes:
      - ./kong.config.sh:/opt/kong.config.sh:Z

  flowbroker-redis:
    image: <private-docker-registry>dojotraining/redis:training-122018
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  flowbroker:
    image: <private-docker-registry>dojotraining/flowbroker:training-122018
    restart: always
    environment:
      DEPLOY_ENGINE: "docker"
      FLOWBROKER_NETWORK: ${FLOWBROKER_NETWORK}
    depends_on:
      - rabbitmq
      - kafka
      - mongodb
      - auth
      - flowbroker-context-manager
      - flowbroker-redis
    networks:
      - default
      - flowbroker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z

  flowbroker-context-manager:
    image: <private-docker-registry>dojotraining/flowbroker-context-manager:training-122018
    restart: always
    environment:
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
      ZEROMQ_PORT: 5556
      HOLD_LOCK_TIMEOUT: 10000
      WAIT_LOCK_TIMEOUT: 30000
    depends_on:
      - zookeeper
    networks:
      - default
      - flowbroker

  rabbitmq:
    image: <private-docker-registry>dojotraining/rabbitmq:training-122018
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  zookeeper:
    image: "<private-docker-registry>dojotraining/zookeeper:training-122018"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  kafka:
    image: "<private-docker-registry>dojotraining/kafka:training-122018"
    depends_on:
      - zookeeper
    restart: always
    environment:
      ZOOKEEPER_IP: zookeeper
      KAFKA_NUM_PARTITIONS: 10
    logging:
      driver: json-file
      options:
        max-size: 100m

