  iotagent-http:
    image: dojot-training/iotagent-http
    depends_on:
      - kafka
      - data-broker
      - auth
    ports:
      - 3124:3124
    restart: always
    environment:
      DOJOT_SERVICE_MANAGEMENT: 'internal'
      SERVER_PORT: 3124
    logging:
      driver: json-file
      options:
        max-size: 100m

