  mosca-redis:
    image: <image-docker-registry>dojotraining/redis:training-20190131
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  iotagent-mqtt:
    image: <image-docker-registry>dojotraining/iotagent-mosca:training-20190131
    depends_on:
      - mosca-redis
      - kafka
      - data-broker
      - auth
    ports:
      - 1883:1883
      - 8883:8883
    restart: always
    environment:
      DOJOT_MANAGEMENT_TENANT: 'internal'
      KAFKA_GROUP_ID: 'data-broker.group'
    logging:
      driver: json-file
      options:
        max-size: 100m

