version: '2.1'
services:

  history:
    image: <image-docker-registry>dojotraining/history:training-20190131
    restart: always
    depends_on:
      - mongodb
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_SERVICE_MANAGEMENT: 'internal'
    logging:
      driver: json-file
      options:
        max-size: 100m

  persister:
    image: <image-docker-registry>dojotraining/persister:training-20190131
    restart: always
    depends_on:
      - mongodb
      - auth
      - kafka
      - data-broker
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_MANAGEMENT_TENANT: 'internal'
      KAFKA_GROUP_ID: 'persister.group'
    logging:
      driver: json-file
      options:
        max-size: 100m

  mongodb:
    image: "<image-docker-registry>dojotraining/mongo:training-20190131"
    restart: always
    user: "mongodb"
    logging:
      driver: json-file
      options:
        max-size: 100m

  gui:
    image: <image-docker-registry>dojotraining/gui:training-20190131
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  data-broker:
    image: <image-docker-registry>dojotraining/data-broker:training-20190131
    restart: always
    depends_on:
      - kafka
      - data-broker-redis
    logging:
      driver: json-file
      options:
        max-size: 100m
    environment:
      DOJOT_SERVICE_MANAGEMENT: 'internal'
      DOJOT_MANAGEMENT_TENANT: 'internal'
      KAFKA_GROUP_ID: 'data-broker.group'

  data-broker-redis:
    image: <image-docker-registry>dojotraining/redis:training-20190131
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  device-manager-redis:
    image: <image-docker-registry>dojotraining/redis:training-20190131
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  device-manager:
    image: <image-docker-registry>dojotraining/device-manager:training-20190131
    restart: always
    environment:
      # TODO: Fill these env variables with suitable values
      - DEV_MNGR_CRYPTO_PASS="kamehameHA"
      - DEV_MNGR_CRYPTO_IV=1234567890123456
      - DEV_MNGR_CRYPTO_SALT="shuriken"
    depends_on:
      - postgres
      - kafka
      - data-broker
      - device-manager-redis
    logging:
      driver: json-file
      options:
        max-size: 100m

  auth-redis:
    image: <image-docker-registry>dojotraining/redis:training-20190131
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  auth:
    image: <image-docker-registry>dojotraining/auth:training-20190131
    restart: always
    depends_on:
      - apigw
      - postgres
      - auth-redis
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AUTH_DB_HOST: "postgres"
      AUTH_DB_USER: "kong"
      AUTH_KONG_URL: "http://apigw:8001"
      AUTH_CACHE_HOST: "auth-redis"
      # This is used to select the type of cache to be used. Allowed values are "redis" or "nocache"
      AUTH_CACHE_NAME: "redis"
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres:
    image: "<image-docker-registry>dojotraining/postgres:training-20190131"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres-users:
    image: "<image-docker-registry>dojotraining/postgres:training-20190131"
    restart: on-failure
    command: >
      bash -c "if ! psql -h postgres -U postgres -t -c '\du' | cut -d \| -f 1 | grep -qw kong; then
                   echo 'creating user kong'
                   createuser kong -d -h postgres -U postgres
               else
                   echo 'user kong exists'
               fi
               if ! psql -h postgres -U postgres -lqt | cut -d \| -f 1 | grep -qw kong; then
                   echo 'creating database kong'
                   createdb kong -U kong -h postgres
               else
                   echo 'database kong exists'
               fi"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-migration:
    image: <image-docker-registry>dojotraining/kong:training-20190131
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
    command: kong migrations up
    restart: on-failure

  apigw:
    image: <image-docker-registry>dojotraining/kong:training-20190131
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "postgres"
    volumes:
      - ./apigw/plugins/pep-kong:/plugins/pep-kong:Z
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-config:
    image: <image-docker-registry>dojotraining/curl:training-20190131
    entrypoint: /opt/kong.config.sh
    restart: on-failure
    depends_on:
      - apigw
    volumes:
      - ./kong.config.sh:/opt/kong.config.sh:Z

  flowbroker-redis:
    image: <image-docker-registry>dojotraining/redis:training-20190131
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  flowbroker:
    image: <image-docker-registry>dojotraining/flowbroker:training-20190131
    restart: always
    environment:
      DEPLOY_ENGINE: "docker"
      FLOWBROKER_NETWORK: ${FLOWBROKER_NETWORK}
      DOJOT_SERVICE_MANAGEMENT: 'internal'
    depends_on:
      - rabbitmq
      - kafka
      - mongodb
      - auth
      - flowbroker-context-manager
      - flowbroker-redis
    networks:
      - default
      - flowbroker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z

  flowbroker-context-manager:
    image: <image-docker-registry>dojotraining/flowbroker-context-manager:training-20190131
    restart: always
    environment:
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
      ZEROMQ_PORT: 5556
      HOLD_LOCK_TIMEOUT: 10000
      WAIT_LOCK_TIMEOUT: 30000
    depends_on:
      - zookeeper
    networks:
      - default
      - flowbroker

  rabbitmq:
    image: <image-docker-registry>dojotraining/rabbitmq:training-20190131
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  zookeeper:
    image: "<image-docker-registry>dojotraining/zookeeper:training-20190131"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  kafka:
    image: "<image-docker-registry>dojotraining/kafka:training-20190131"
    depends_on:
      - zookeeper
    restart: always
    environment:
      ZOOKEEPER_IP: zookeeper
      KAFKA_NUM_PARTITIONS: 10
    logging:
      driver: json-file
      options:
        max-size: 100m

